
CREATE TABLE IF NOT EXISTS vocab_sets (
    id SERIAL PRIMARY KEY,
    account_id TEXT,
    title TEXT NOT NULL,
    terms TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
